# Obstacles configuration file
# Defines obstacles for each map

map1_obstacles:
  obstacles:
    - type: "border"
      coordinates: [0.0, 0.0, 3.2, 6.0]  # [x1, y1, x2, y2] in meters
    - type: "recover"
      coordinates: [0.0, 0.0, 1.0, 1.0]  # [x1, y1, x2, y2] in meters
    - type: "filled"
      coordinates: [0.0, 2.2, 0.3, 3.0]  # [x1, y1, x2, y2] in meters
    - type: "recover"
      coordinates: [0.0, 4.2, 0.8, 5.0]  # [x1, y1, x2, y2] in meters
    - type: "filled"
      coordinates: [0.35, 5.875, 1.55, 6.0]  # [x1, y1, x2, y2] in meters
    - type: "filled"
      coordinates: [2.0, 0.0, 2.0, 1.2]  # [x1, y1, x2, y2] in meters
    - type: "filled"
      coordinates: [2.0, 4.8, 2.0, 6.0]  # [x1, y1, x2, y2] in meters
    - type: "filled"
      coordinates: [2.0, 1.1, 3.2, 1.3]  # [x1, y1, x2, y2] in meters
    - type: "filled"
      coordinates: [2.0, 4.7, 3.2, 4.9]  # [x1, y1, x2, y2] in meters
    - type: "erase"
      coordinates: [3.2, 1.2, 3.2, 4.8]  # [x1, y1, x2, y2] in meters
      

map2_obstacles:
  obstacles: 

map3_obstacles:
  obstacles:
    - type: "border"
      coordinates: [0.0, 0.0, 4.0, 6.0]  # [x1, y1, x2, y2] in meters
    - type: "erase"
      coordinates: [0.0, 1.2, 0.0, 4.8]  # [x1, y1, x2, y2] in meters
    - type: "filled"
      coordinates: [0.0, 0.0, 0.0, 1.2]
    - type: "filled"
      coordinates: [0.0, 4.8, 1.44, 4.8]
    - type: "filled"
      coordinates: [1.3, 1.5, 2.75, 1.5]
    - type: "filled"
      coordinates: [1.45, 1.5, 1.45, 6.0]
    - type: "filled"
      coordinates: [1.45, 3.5, 1.75, 5.0]
    - type: "recover"
      coordinates: [3.0, 0.0, 4.0, 1.0]

